In [1]:
import pandas as pd
import numpy as np

In [2]:
df_trips = pd.read_csv('trippub.csv', low_memory = False)
df_pers = pd.read_csv('perpub.csv', low_memory = False)
df_hh = pd.read_csv('hhpub.csv', low_memory = False)

In [3]:
print(df_trips.shape)
print(df_pers.shape)
print(df_hh.shape)

(923572, 115)
(264234, 121)
(129696, 58)

In [4]:
df_trips.head(10)

,HOUSEID,PERSONID,TDTRPNUM,STRTTIME,ENDTIME,TRVLCMIN,TRPMILES,TRPTRANS,TRPACCMP,TRPHHACC,...,OBHTNRNT,OBPPOPDN,OBRESDN,DTHTNRNT,DTPPOPDN,DTRESDN,DTEEMPDN,DBHTNRNT,DBPPOPDN,DBRESDN
0,30000007,1,1,1000,1015,15,5.244,3,0,0,...,20,750,300,50,750,300,350,30,300,300
1,30000007,1,2,1510,1530,20,5.149,3,0,0,...,30,300,300,50,1500,750,750,20,750,300
2,30000007,2,1,700,900,120,84.004,6,0,0,...,40,1500,750,50,1500,750,750,20,750,300
3,30000007,2,2,1800,2030,150,81.628,6,0,0,...,20,750,300,40,1500,750,750,40,1500,750
4,30000007,3,1,845,900,15,2.250,3,0,0,...,20,750,300,50,750,300,350,60,750,300
5,30000007,3,2,1430,1445,15,2.243,3,0,0,...,60,750,300,50,1500,750,750,20,750,300
6,30000008,1,1,1115,1130,15,8.017,6,0,0,...,5,300,300,30,300,300,150,40,1500,750
7,30000008,1,2,2330,2340,10,8.017,6,0,0,...,40,1500,750,5,300,300,150,5,300,300
8,30000012,1,1,550,605,15,3.395,4,0,0,...,60,17000,7000,30,750,300,350,5,750,300
9,30000012,1,2,700,715,15,3.395,4,0,0,...,5,750,300,80,17000,17000,5000,60,17000,7000

In [5]:
df_trips.isnull().sum()

HOUSEID     0
PERSONID    0
TDTRPNUM    0
STRTTIME    0
ENDTIME     0
           ..
DTRESDN     0
DTEEMPDN    0
DBHTNRNT    0
DBPPOPDN    0
DBRESDN     0
Length: 115, dtype: int64

In [6]:
print([col for col in df_trips.columns if 'WHY' in col])

['WHYFROM', 'WHYTRP1S', 'WHYTO', 'WHYTRP90']

In [7]:
df_trips.columns

Index(['HOUSEID', 'PERSONID', 'TDTRPNUM', 'STRTTIME', 'ENDTIME', 'TRVLCMIN',
       'TRPMILES', 'TRPTRANS', 'TRPACCMP', 'TRPHHACC',
       ...
       'OBHTNRNT', 'OBPPOPDN', 'OBRESDN', 'DTHTNRNT', 'DTPPOPDN', 'DTRESDN',
       'DTEEMPDN', 'DBHTNRNT', 'DBPPOPDN', 'DBRESDN'],
      dtype='object', length=115)

In [10]:
df_pers.head()

,HOUSEID,PERSONID,R_AGE,EDUC,R_HISP,R_RELAT,R_SEX,R_RACE,PRMACT,PAYPROF,...,SMPLSRCE,WTPERFIN,HBHUR,HTHTNRNT,HTPPOPDN,HTRESDN,HTEEMPDN,HBHTNRNT,HBPPOPDN,HBRESDN
0,30000007,1,67.0,3.0,2.0,1.0,2.0,2.0,6.0,2.0,...,2,206.690153,T,50.0,1500.0,750.0,750.0,20.0,750.0,300.0
1,30000007,2,66.0,3.0,2.0,2.0,1.0,2.0,1.0,NaN,...,2,197.075742,T,50.0,1500.0,750.0,750.0,20.0,750.0,300.0
2,30000007,3,28.0,2.0,2.0,3.0,2.0,2.0,5.0,2.0,...,2,219.514210,T,50.0,1500.0,750.0,750.0,20.0,750.0,300.0
3,30000008,1,55.0,5.0,2.0,1.0,1.0,1.0,1.0,NaN,...,2,63.185911,R,5.0,300.0,300.0,150.0,5.0,300.0,300.0
4,30000008,2,49.0,4.0,2.0,2.0,2.0,1.0,1.0,NaN,...,2,58.665911,R,5.0,300.0,300.0,150.0,5.0,300.0,300.0

In [11]:
missing_codes = [-1, -7, -8, -9, -88, -99]
for df in [df_trips, df_pers, df_hh]:
    df.replace(missing_codes, np.nan, inplace=True)

In [12]:
df_pers.head(10)

,HOUSEID,PERSONID,R_AGE,EDUC,R_HISP,R_RELAT,R_SEX,R_RACE,PRMACT,PAYPROF,...,SMPLSRCE,WTPERFIN,HBHUR,HTHTNRNT,HTPPOPDN,HTRESDN,HTEEMPDN,HBHTNRNT,HBPPOPDN,HBRESDN
0,30000007,1,67.0,3.0,2.0,1.0,2.0,2.0,6.0,2.0,...,2,206.690153,T,50.0,1500.0,750.0,750.0,20.0,750.0,300.0
1,30000007,2,66.0,3.0,2.0,2.0,1.0,2.0,1.0,NaN,...,2,197.075742,T,50.0,1500.0,750.0,750.0,20.0,750.0,300.0
2,30000007,3,28.0,2.0,2.0,3.0,2.0,2.0,5.0,2.0,...,2,219.514210,T,50.0,1500.0,750.0,750.0,20.0,750.0,300.0
3,30000008,1,55.0,5.0,2.0,1.0,1.0,1.0,1.0,NaN,...,2,63.185911,R,5.0,300.0,300.0,150.0,5.0,300.0,300.0
4,30000008,2,49.0,4.0,2.0,2.0,2.0,1.0,1.0,NaN,...,2,58.665911,R,5.0,300.0,300.0,150.0,5.0,300.0,300.0
5,30000012,1,45.0,5.0,2.0,1.0,2.0,1.0,1.0,NaN,...,2,58.966275,C,80.0,17000.0,17000.0,5000.0,60.0,17000.0,7000.0
6,30000019,1,68.0,1.0,2.0,1.0,1.0,1.0,97.0,2.0,...,2,233.138565,S,40.0,300.0,300.0,150.0,50.0,750.0,300.0
7,30000019,2,66.0,2.0,2.0,2.0,2.0,1.0,4.0,2.0,...,2,249.148185,S,40.0,300.0,300.0,150.0,50.0,750.0,300.0
8,30000029,1,72.0,3.0,2.0,1.0,1.0,1.0,6.0,2.0,...,2,91.407643,S,40.0,1500.0,750.0,750.0,40.0,1500.0,750.0
9,30000029,2,72.0,2.0,2.0,2.0,2.0,1.0,6.0,2.0,...,2,96.249289,S,40.0,1500.0,750.0,750.0,40.0,1500.0,750.0

In [13]:
hh_cols = ['HOUSEID', 'HHFAMINC', 'HHVEHCNT', 'HHSIZE', 'URBAN', 'HOMEOWN', 'TRAVDAY']

In [14]:
df_hh_filt = df_hh[hh_cols].copy()

In [15]:
per_cols = ['HOUSEID', 'PERSONID', 'R_SEX', 'R_AGE', 'PRMACT', 'WORKER', 'EDUC','PAYPROF', 'DRIVER']
df_per_filt = df_pers[per_cols].copy()
df_per_filt['SEX'] = df_per_filt['R_SEX'].map({1:0, 2:1})
df_per_filt = df_per_filt.drop('R_SEX', axis=1)

In [16]:
trip_cols = ['HOUSEID', 'PERSONID', 'TRPTRANS', 'TRVLCMIN', 'TRPMILES', 'DWELTIME', 'WHYTO', 'TRAVDAY' , 'URBRUR']
df_trips_filt = df_trips[trip_cols].copy()

In [17]:
df_temp_1 = pd.merge(df_trips_filt, df_per_filt, on=['HOUSEID','PERSONID', 'TRAVDAY'], how='left')

trip_data = pd.merge(df_temp_1, df_hh_filt, on = 'HOUSEID', how='left')

In [18]:
trip_data.head()

,HOUSEID,PERSONID,TRPTRANS,TRVLCMIN,TRPMILES,STRTTIME,WHYTRP1S,DWELTIME,WHYFROM,WHYTO,...,TRAVDAY_y,HBRESDN,HBHUR,HTHTNRNT,HTPPOPDN,HTRESDN,HTEEMPDN,HBHTNRNT,HBPPOPDN,HBRESDN
0,30000007,1,3.0,15.0,5.244,1000,20,295.0,1.0,19.0,...,2,300.0,T,50.0,1500.0,750.0,750.0,20.0,750.0,300.0
1,30000007,1,3.0,20.0,5.149,1510,1,NaN,19.0,1.0,...,2,300.0,T,50.0,1500.0,750.0,750.0,20.0,750.0,300.0
2,30000007,2,6.0,120.0,84.004,700,1,540.0,3.0,1.0,...,2,300.0,T,50.0,1500.0,750.0,750.0,20.0,750.0,300.0
3,30000007,2,6.0,150.0,81.628,1800,10,NaN,1.0,3.0,...,2,300.0,T,50.0,1500.0,750.0,750.0,20.0,750.0,300.0
4,30000007,3,3.0,15.0,2.250,845,20,330.0,1.0,8.0,...,2,300.0,T,50.0,1500.0,750.0,750.0,20.0,750.0,300.0

In [19]:
print(trip_data.isnull().sum())

HOUSEID           0
PERSONID          0
TRPTRANS         16
TRVLCMIN       1297
TRPMILES        656
STRTTIME          0
WHYTRP1S          0
DWELTIME     219200
WHYFROM         239
WHYTO           232
TRAVDAY_x         0
OBRESDN         980
DBRESDN         962
DTEEMPDN        955
ENDTIME           0
R_AGE          1216
PRMACT        79373
WORKER        79323
EDUC          65579
PAYPROF      508915
DRIVER        71889
SEX             711
HHFAMINC      24340
HHVEHCNT          0
HHSIZE            0
URBAN             0
URBANSIZE         0
HOMEOWN         162
TRAVDAY_y         0
HBRESDN         736
HBHUR             0
HTHTNRNT        736
HTPPOPDN        736
HTRESDN         736
HTEEMPDN        736
HBHTNRNT        736
HBPPOPDN        736
HBRESDN         736
dtype: int64

In [20]:
trip_data.isnull().sum() / len(trip_data) * 100

HOUSEID       0.000000
PERSONID      0.000000
TRPTRANS      0.001732
TRVLCMIN      0.140433
TRPMILES      0.071029
STRTTIME      0.000000
WHYTRP1S      0.000000
DWELTIME     23.733937
WHYFROM       0.025878
WHYTO         0.025120
TRAVDAY_x     0.000000
OBRESDN       0.106110
DBRESDN       0.104161
DTEEMPDN      0.103403
ENDTIME       0.000000
R_AGE         0.131663
PRMACT        8.594132
WORKER        8.588719
EDUC          7.100583
PAYPROF      55.102905
DRIVER        7.783800
SEX           0.076984
HHFAMINC      2.635420
HHVEHCNT      0.000000
HHSIZE        0.000000
URBAN         0.000000
URBANSIZE     0.000000
HOMEOWN       0.017541
TRAVDAY_y     0.000000
HBRESDN       0.079691
HBHUR         0.000000
HTHTNRNT      0.079691
HTPPOPDN      0.079691
HTRESDN       0.079691
HTEEMPDN      0.079691
HBHTNRNT      0.079691
HBPPOPDN      0.079691
HBRESDN       0.079691
dtype: float64

In [24]:
trip_data = trip_data.dropna(subset=['TRPTRANS', 'TRVLCMIN', 'TRPMILES', 'R_AGE', 'PRMACT', 'WORKER', 'EDUC'])

In [27]:
trip_data.columns

Index(['HOUSEID', 'PERSONID', 'TRPTRANS', 'TRVLCMIN', 'TRPMILES', 'STRTTIME',
       'WHYTRP1S', 'WHYFROM', 'WHYTO', 'TRAVDAY_x', 'ENDTIME', 'R_AGE',
       'PRMACT', 'WORKER', 'EDUC', 'DRIVER', 'SEX', 'HHFAMINC', 'HHVEHCNT',
       'HHSIZE', 'URBAN', 'URBANSIZE', 'HOMEOWN', 'TRAVDAY_y', 'HBHUR',
       'HTHTNRNT', 'HTPPOPDN'],
      dtype='object')

In [29]:
trip_data['TRAVDAY'] = trip_data['TRAVDAY'].map({1:0, 2:1})

0         2
1         2
2         2
3         2
4         2
         ..
923567    3
923568    3
923569    3
923570    3
923571    3
Name: TRAVDAY_x, Length: 840934, dtype: int64

In [ ]:
trip_data['TRAVDAY

In [ ]:
weekday_averages

In [ ]:
def estimate_cost(row):
    # If they took a car (Codes 03-06)
    if row['TRPTRANS'] in [3, 4, 5, 6]:
        cost = row['TRPMILES'] * 0.18 # Estimated parking fee
        return cost
    # If they took transit (Codes 10-16)
    elif 10 <= row['TRPTRANS'] <= 16:
        return 2.50 # Standard fare estimate
    return 0

df['trip_cost'] = df.apply(estimate_cost, axis=1)

In [ ]:
def get_period(hr):
    if 6 <= hr <= 9: return 'AM_Peak'
    if 15 <= hr <= 19: return 'PM_Peak'
    if 9 < hr < 15: return 'Mid_Day'
    return 'Night'

df['time_period'] = (df['STRTTIME'] // 100).apply(get_period)

In [ ]:
# Fix 1 — HHFAMINC income bracket to midpoint
income_map = {
    1: 5000,   2: 12500,  3: 20000,  4: 30000,   5: 42500,
    6: 62500,  7: 87500,  8: 112500, 9: 137500, 10: 175000, 11: 225000
}
df["income"] = df["HHFAMINC"].map(income_map)

In [ ]:
# Create a lean mapping
summary_purpose_map = {
    1: 'Work',
    10: 'Home',
    20: 'Shop',
    30: 'Personal',
    40: 'School',
    50: 'Medical',
    70: 'Social',
    80: 'Other',
    97: 'Other'
}

# Apply the map
df['TRPPRP'] = df['WHYTRP1S'].map(summary_purpose_map)