In [1]:
import pandas as pd
import numpy as np

In [2]:
df_trips = pd.read_csv('raw_dataset/trippub.csv', low_memory = False)
df_pers = pd.read_csv('raw_dataset/perpub.csv', low_memory = False)
df_hh = pd.read_csv('raw_dataset/hhpub.csv', low_memory = False)

In [3]:
print(df_trips.shape)
print(df_pers.shape)
print(df_hh.shape)

(923572, 115)
(264234, 121)
(129696, 58)

In [4]:
df_trips.head(10)

,HOUSEID,PERSONID,TDTRPNUM,STRTTIME,ENDTIME,TRVLCMIN,TRPMILES,TRPTRANS,TRPACCMP,TRPHHACC,...,OBHTNRNT,OBPPOPDN,OBRESDN,DTHTNRNT,DTPPOPDN,DTRESDN,DTEEMPDN,DBHTNRNT,DBPPOPDN,DBRESDN
0,30000007,1,1,1000,1015,15,5.244,3,0,0,...,20,750,300,50,750,300,350,30,300,300
1,30000007,1,2,1510,1530,20,5.149,3,0,0,...,30,300,300,50,1500,750,750,20,750,300
2,30000007,2,1,700,900,120,84.004,6,0,0,...,40,1500,750,50,1500,750,750,20,750,300
3,30000007,2,2,1800,2030,150,81.628,6,0,0,...,20,750,300,40,1500,750,750,40,1500,750
4,30000007,3,1,845,900,15,2.250,3,0,0,...,20,750,300,50,750,300,350,60,750,300
5,30000007,3,2,1430,1445,15,2.243,3,0,0,...,60,750,300,50,1500,750,750,20,750,300
6,30000008,1,1,1115,1130,15,8.017,6,0,0,...,5,300,300,30,300,300,150,40,1500,750
7,30000008,1,2,2330,2340,10,8.017,6,0,0,...,40,1500,750,5,300,300,150,5,300,300
8,30000012,1,1,550,605,15,3.395,4,0,0,...,60,17000,7000,30,750,300,350,5,750,300
9,30000012,1,2,700,715,15,3.395,4,0,0,...,5,750,300,80,17000,17000,5000,60,17000,7000

In [5]:
df_trips.isnull().sum()

HOUSEID     0
PERSONID    0
TDTRPNUM    0
STRTTIME    0
ENDTIME     0
           ..
DTRESDN     0
DTEEMPDN    0
DBHTNRNT    0
DBPPOPDN    0
DBRESDN     0
Length: 115, dtype: int64

In [6]:
print([col for col in df_trips.columns if 'WHY' in col])

['WHYFROM', 'WHYTRP1S', 'WHYTO', 'WHYTRP90']

In [7]:
df_trips.columns

Index(['HOUSEID', 'PERSONID', 'TDTRPNUM', 'STRTTIME', 'ENDTIME', 'TRVLCMIN',
       'TRPMILES', 'TRPTRANS', 'TRPACCMP', 'TRPHHACC',
       ...
       'OBHTNRNT', 'OBPPOPDN', 'OBRESDN', 'DTHTNRNT', 'DTPPOPDN', 'DTRESDN',
       'DTEEMPDN', 'DBHTNRNT', 'DBPPOPDN', 'DBRESDN'],
      dtype='object', length=115)

In [8]:
df_pers.head()

,HOUSEID,PERSONID,R_AGE,EDUC,R_HISP,R_RELAT,R_SEX,R_RACE,PRMACT,PAYPROF,...,SMPLSRCE,WTPERFIN,HBHUR,HTHTNRNT,HTPPOPDN,HTRESDN,HTEEMPDN,HBHTNRNT,HBPPOPDN,HBRESDN
0,30000007,1,67,3,2,1,2,2,6,2,...,2,206.690153,T,50,1500,750,750,20,750,300
1,30000007,2,66,3,2,2,1,2,1,-1,...,2,197.075742,T,50,1500,750,750,20,750,300
2,30000007,3,28,2,2,3,2,2,5,2,...,2,219.514210,T,50,1500,750,750,20,750,300
3,30000008,1,55,5,2,1,1,1,1,-1,...,2,63.185911,R,5,300,300,150,5,300,300
4,30000008,2,49,4,2,2,2,1,1,-1,...,2,58.665911,R,5,300,300,150,5,300,300

In [9]:
df_pers['R_SEX'].unique()

array([ 2,  1, -7, -8])

In [10]:
missing_codes = [-1, -7, -8, -9, -88, -99]
for df in [df_trips, df_pers, df_hh]:
    df.replace(missing_codes, np.nan, inplace=True)

In [11]:
df_pers.head(10)

,HOUSEID,PERSONID,R_AGE,EDUC,R_HISP,R_RELAT,R_SEX,R_RACE,PRMACT,PAYPROF,...,SMPLSRCE,WTPERFIN,HBHUR,HTHTNRNT,HTPPOPDN,HTRESDN,HTEEMPDN,HBHTNRNT,HBPPOPDN,HBRESDN
0,30000007,1,67.0,3.0,2.0,1.0,2.0,2.0,6.0,2.0,...,2,206.690153,T,50.0,1500.0,750.0,750.0,20.0,750.0,300.0
1,30000007,2,66.0,3.0,2.0,2.0,1.0,2.0,1.0,NaN,...,2,197.075742,T,50.0,1500.0,750.0,750.0,20.0,750.0,300.0
2,30000007,3,28.0,2.0,2.0,3.0,2.0,2.0,5.0,2.0,...,2,219.514210,T,50.0,1500.0,750.0,750.0,20.0,750.0,300.0
3,30000008,1,55.0,5.0,2.0,1.0,1.0,1.0,1.0,NaN,...,2,63.185911,R,5.0,300.0,300.0,150.0,5.0,300.0,300.0
4,30000008,2,49.0,4.0,2.0,2.0,2.0,1.0,1.0,NaN,...,2,58.665911,R,5.0,300.0,300.0,150.0,5.0,300.0,300.0
5,30000012,1,45.0,5.0,2.0,1.0,2.0,1.0,1.0,NaN,...,2,58.966275,C,80.0,17000.0,17000.0,5000.0,60.0,17000.0,7000.0
6,30000019,1,68.0,1.0,2.0,1.0,1.0,1.0,97.0,2.0,...,2,233.138565,S,40.0,300.0,300.0,150.0,50.0,750.0,300.0
7,30000019,2,66.0,2.0,2.0,2.0,2.0,1.0,4.0,2.0,...,2,249.148185,S,40.0,300.0,300.0,150.0,50.0,750.0,300.0
8,30000029,1,72.0,3.0,2.0,1.0,1.0,1.0,6.0,2.0,...,2,91.407643,S,40.0,1500.0,750.0,750.0,40.0,1500.0,750.0
9,30000029,2,72.0,2.0,2.0,2.0,2.0,1.0,6.0,2.0,...,2,96.249289,S,40.0,1500.0,750.0,750.0,40.0,1500.0,750.0

In [12]:
hh_cols = ['HOUSEID', 'HHFAMINC', 'HHVEHCNT', 'HHSIZE', 'URBAN', 'HOMEOWN']

In [13]:
df_hh_filt = df_hh[hh_cols].copy()

In [14]:
per_cols = ['HOUSEID', 'PERSONID', 'R_SEX', 'R_AGE', 'PRMACT', 'WORKER', 'EDUC','PAYPROF', 'DRIVER']
df_per_filt = df_pers[per_cols].copy()
df_per_filt['SEX'] = df_per_filt['R_SEX'].map({1:'Male', 2:'Female'})
df_per_filt = df_per_filt.drop('R_SEX', axis=1)

In [15]:
trip_cols = ['HOUSEID', 'PERSONID', 'TRPTRANS', 'TRVLCMIN', 'TRPMILES', 'DWELTIME', 'WHYTO', 'TRAVDAY' , 'URBRUR']
df_trips_filt = df_trips[trip_cols].copy()

In [16]:
df_temp_1 = pd.merge(df_trips_filt, df_per_filt, on=['HOUSEID','PERSONID'], how='left')

trip_data = pd.merge(df_temp_1, df_hh_filt, on = 'HOUSEID', how='left')

In [17]:
trip_data.head()

,HOUSEID,PERSONID,TRPTRANS,TRVLCMIN,TRPMILES,DWELTIME,WHYTO,TRAVDAY,URBRUR,R_AGE,...,WORKER,EDUC,PAYPROF,DRIVER,SEX,HHFAMINC,HHVEHCNT,HHSIZE,URBAN,HOMEOWN
0,30000007,1,3.0,15.0,5.244,295.0,19.0,2,1,67.0,...,2.0,3.0,2.0,1.0,Female,7.0,5,3,1,1.0
1,30000007,1,3.0,20.0,5.149,NaN,1.0,2,1,67.0,...,2.0,3.0,2.0,1.0,Female,7.0,5,3,1,1.0
2,30000007,2,6.0,120.0,84.004,540.0,1.0,2,1,66.0,...,1.0,3.0,NaN,1.0,Male,7.0,5,3,1,1.0
3,30000007,2,6.0,150.0,81.628,NaN,3.0,2,1,66.0,...,1.0,3.0,NaN,1.0,Male,7.0,5,3,1,1.0
4,30000007,3,3.0,15.0,2.250,330.0,8.0,2,1,28.0,...,2.0,2.0,2.0,1.0,Female,7.0,5,3,1,1.0

In [18]:
trip_data['SEX'].unique()

array(['Female', 'Male', nan], dtype=object)

In [19]:
print(trip_data.isnull().sum())

HOUSEID          0
PERSONID         0
TRPTRANS        16
TRVLCMIN      1297
TRPMILES       656
DWELTIME    219200
WHYTO          232
TRAVDAY          0
URBRUR           0
R_AGE         1216
PRMACT       79373
WORKER       79323
EDUC         65579
PAYPROF     508915
DRIVER       71889
SEX            711
HHFAMINC     24340
HHVEHCNT         0
HHSIZE           0
URBAN            0
HOMEOWN        162
dtype: int64

In [20]:
trip_data.isnull().sum() / len(trip_data) * 100

HOUSEID      0.000000
PERSONID     0.000000
TRPTRANS     0.001732
TRVLCMIN     0.140433
TRPMILES     0.071029
DWELTIME    23.733937
WHYTO        0.025120
TRAVDAY      0.000000
URBRUR       0.000000
R_AGE        0.131663
PRMACT       8.594132
WORKER       8.588719
EDUC         7.100583
PAYPROF     55.102905
DRIVER       7.783800
SEX          0.076984
HHFAMINC     2.635420
HHVEHCNT     0.000000
HHSIZE       0.000000
URBAN        0.000000
HOMEOWN      0.017541
dtype: float64

In [21]:
trip_data = trip_data.rename(columns={'DRIVER' : 'CAN-DRIVER'})

In [22]:
trip_data.columns

Index(['HOUSEID', 'PERSONID', 'TRPTRANS', 'TRVLCMIN', 'TRPMILES', 'DWELTIME',
       'WHYTO', 'TRAVDAY', 'URBRUR', 'R_AGE', 'PRMACT', 'WORKER', 'EDUC',
       'PAYPROF', 'CAN-DRIVER', 'SEX', 'HHFAMINC', 'HHVEHCNT', 'HHSIZE',
       'URBAN', 'HOMEOWN'],
      dtype='object')

In [23]:
trip_data['TRAVDAY'] = trip_data['TRAVDAY'].map({1:'Sunday', 2:'Monday',3:'Tuesday',4:'Wednesday',5:'Thursday',6:'Friday',7:'Saturday'})

In [24]:
trip_data.shape

(923572, 21)

In [25]:
trip_data.to_csv('trip_data.csv', index=False)